### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lexleongnotluthor** [nmquijada/ChroQueTas#2]
Hi Narciso, I am having trouble installing ChroQueTas onto our server. I have the admin right to miniconda, and i get this error when trying to install or create an env for ChroQueTas.

> PackagesNotFoundError: The following packages are not available from current channels:
 >- nmquijada::chroquetas

**Comment by nmquijada** [comment]
Hi @lexleongnotluthor 

Thanks for your question. ChroQueTas is still not available as a conda package, as we are preparing and update to include the "degree of evidence" of the different mutations, which is needed for the proper interpretation of the results (as stated in the [preprint](https://www.biorxiv.org/content/10.1101/2024.10.07.617009v1)). We will release the conda package together with the next version.

In the meantime, please install ChroQueTas following the [source code instructions](https://github.com/nmquijada/ChroQueTas?tab=readme-ov-file#33-via-source-code)

Let us know if you encounter further issues!

Best,
N

**Comment by lexleongnotluthor** [comment]
Thanks for your prompt reply, @nmquijada ! I have git pulled it. 
I was in conversation with Joanne last week. My group is not working on mostly AMR for Trichophyton, C. auris and Aspergillus. Will these fungi be rolled out in future db update? I don't supposed that we can use C. albican for C. auris? 
Cheerio, Lx
